### ISSUE TITLE
Consider adding a default accumulator argument to 'traverse'

### ISSUE THREAD

**Issue by ont-app** [ont-app/igraph#4]
At present `traverse` can take 4 or 5 arguments, with the 4-arg version implying an empty context map. There could be a 3-arg variant with implied empty context map, and implied empty set as the accumulator.

Done when
- (traverse _g_ _traverse-fn_ _queue_) is an option when calling traverse.
- This feature has been documented and tested.

Thanks to Gavin Matthews for the suggestion.

**Comment by simongray** [comment]
I think this is a good idea since I already tire of filling the arglist with empty data structures :P

Why default to a set rather than a vector, though? If you provide a vector you can see the traversed path for e.g. a transitive closure, while using set will erase this information.

Obviously, correct me if I'm wrong about my assumptions. I only just started using the library and I am definitely not as knowledgeable about graphs or RDF as you are.

**Comment by ont-app** [comment]
I see your point about using a vector as default accumulator. Thanks!

**Comment by ericdscott** [comment]
Fixed with 5b694d0
